part of harvest_place_app;

// ================================================================
// PHASE 4H — FARMER PAYOUT SCHEDULING
// Extends existing Phase 4B settlement batches.
// ================================================================

class FarmerPayoutScheduleSummary{
  final int openCount,unscheduledCount,overdueCount;final double due7,due30,funded,unfunded;
  const FarmerPayoutScheduleSummary({required this.openCount,required this.unscheduledCount,required this.overdueCount,required this.due7,required this.due30,required this.funded,required this.unfunded});
  factory FarmerPayoutScheduleSummary.fromSupabase(Map<String,dynamic>d){double n(dynamic v)=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??0;int i(dynamic v)=>v is num?v.toInt():int.tryParse(v?.toString()??'')??0;return FarmerPayoutScheduleSummary(openCount:i(d['open_settlement_count']),unscheduledCount:i(d['unscheduled_count']),overdueCount:i(d['overdue_count']),due7:n(d['due_7_days']),due30:n(d['due_30_days']),funded:n(d['funded_open_amount']),unfunded:n(d['unfunded_open_amount']));}
}
class FarmerPayoutScheduleRow{
  final String id,number,farmerId,farmerName,farmName,status,priority,fundingStatus;final double total;final DateTime? scheduledDate;final int daysUntil,payoutCount;final DateTime? createdAt,approvedAt;
  const FarmerPayoutScheduleRow({required this.id,required this.number,required this.farmerId,required this.farmerName,required this.farmName,required this.status,required this.priority,required this.fundingStatus,required this.total,this.scheduledDate,required this.daysUntil,required this.payoutCount,this.createdAt,this.approvedAt});
  factory FarmerPayoutScheduleRow.fromSupabase(Map<String,dynamic>d){double n(dynamic v)=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??0;int i(dynamic v)=>v is num?v.toInt():int.tryParse(v?.toString()??'')??0;return FarmerPayoutScheduleRow(id:(d['settlement_id']??'').toString(),number:(d['settlement_number']??'').toString(),farmerId:(d['farmer_id']??'').toString(),farmerName:(d['farmer_name']??'Farmer').toString(),farmName:(d['farm_name']??'').toString(),status:(d['status']??'draft').toString(),priority:(d['payout_priority']??'normal').toString(),fundingStatus:(d['funding_status']??'unplanned').toString(),total:n(d['total_amount']),scheduledDate:DateTime.tryParse((d['scheduled_payout_date']??'').toString()),daysUntil:i(d['days_until_payout']),payoutCount:i(d['payout_count']),createdAt:DateTime.tryParse((d['created_at']??'').toString()),approvedAt:DateTime.tryParse((d['approved_at']??'').toString()));}
  String get displayName=>farmName.trim().isEmpty?farmerName:farmName;
}
Future<FarmerPayoutScheduleSummary> fetchFarmerPayoutScheduleSummary()async{await requireAdminAccess();final r=await supabase.rpc('admin_farmer_payout_schedule_summary');if(r is List&&r.isNotEmpty)return FarmerPayoutScheduleSummary.fromSupabase(Map<String,dynamic>.from(r.first as Map));if(r is Map)return FarmerPayoutScheduleSummary.fromSupabase(Map<String,dynamic>.from(r));throw Exception('Payout schedule summary could not be loaded.');}
Future<List<FarmerPayoutScheduleRow>> fetchFarmerPayoutSchedule({String filter='open'})async{await requireAdminAccess();final r=await supabase.rpc('admin_list_farmer_payout_schedule',params:{'p_filter':filter,'p_limit':200});return (r as List).map((e)=>FarmerPayoutScheduleRow.fromSupabase(Map<String,dynamic>.from(e as Map))).toList();}
Future<void> updateFarmerPayoutSchedule({required String settlementId,required DateTime date,required String priority,required String fundingStatus,String notes=''})async{await requireAdminAccess();await supabase.rpc('admin_update_farmer_settlement_schedule',params:{'p_settlement_id':settlementId,'p_scheduled_payout_date':'${date.year.toString().padLeft(4,'0')}-${date.month.toString().padLeft(2,'0')}-${date.day.toString().padLeft(2,'0')}','p_priority':priority,'p_funding_status':fundingStatus,'p_notes':notes.trim()});}
Future<void> clearFarmerPayoutSchedule(String settlementId,String reason)async{await requireAdminAccess();await supabase.rpc('admin_clear_farmer_settlement_schedule',params:{'p_settlement_id':settlementId,'p_reason':reason.trim()});}

class FarmerPayoutScheduleScreen extends StatefulWidget{const FarmerPayoutScheduleScreen({super.key});@override State<FarmerPayoutScheduleScreen> createState()=>_FarmerPayoutScheduleScreenState();}
class _FarmerPayoutScheduleScreenState extends State<FarmerPayoutScheduleScreen>{
  String _filter='open';late Future<List<dynamic>> _future;@override void initState(){super.initState();_future=_load();}Future<List<dynamic>> _load()=>Future.wait<dynamic>([fetchFarmerPayoutScheduleSummary(),fetchFarmerPayoutSchedule(filter:_filter)]);Future<void> _refresh()async{final n=_load();setState(()=>_future=n);await n;}
  String _date(DateTime? d)=>d==null?'Not scheduled':'${d.day}/${d.month}/${d.year}';
  Color _color(FarmerPayoutScheduleRow r){if(r.daysUntil<0&&r.scheduledDate!=null)return FarmColors.danger;if(r.priority=='critical'||r.priority=='high')return FarmColors.warning;if(r.fundingStatus=='funded')return FarmColors.success;return FarmColors.primary;}
  Future<void> _schedule(FarmerPayoutScheduleRow row)async{DateTime selected=row.scheduledDate??DateTime.now();String priority=row.priority;String funding=row.fundingStatus=='unplanned'?'planned':row.fundingStatus;final note=TextEditingController();final ok=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,builder:(sheet)=>StatefulBuilder(builder:(context,setSheet){return SafeArea(child:Padding(padding:EdgeInsets.fromLTRB(18,18,18,MediaQuery.of(sheet).viewInsets.bottom+18),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Schedule ${row.number}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:12),ListTile(contentPadding:EdgeInsets.zero,title:const Text('Payout date'),subtitle:Text(_date(selected)),trailing:const Icon(Icons.calendar_today_outlined),onTap:()async{final picked=await showDatePicker(context:context,initialDate:selected,firstDate:DateTime.now().subtract(const Duration(days:90)),lastDate:DateTime.now().add(const Duration(days:365)));if(picked!=null)setSheet(()=>selected=picked);}),const SizedBox(height:8),DropdownButtonFormField<String>(value:priority,decoration:const InputDecoration(labelText:'Priority'),items:const [DropdownMenuItem(value:'low',child:Text('Low')),DropdownMenuItem(value:'normal',child:Text('Normal')),DropdownMenuItem(value:'high',child:Text('High')),DropdownMenuItem(value:'critical',child:Text('Critical'))],onChanged:(v){if(v!=null)setSheet(()=>priority=v);}),const SizedBox(height:10),DropdownButtonFormField<String>(value:funding,decoration:const InputDecoration(labelText:'Funding status'),items:const [DropdownMenuItem(value:'planned',child:Text('Planned / not yet funded')),DropdownMenuItem(value:'funded',child:Text('Funded')),DropdownMenuItem(value:'unplanned',child:Text('Unplanned'))],onChanged:(v){if(v!=null)setSheet(()=>funding=v);}),const SizedBox(height:10),TextField(controller:note,maxLines:2,decoration:const InputDecoration(labelText:'Schedule note (optional)')),const SizedBox(height:14),SizedBox(width:double.infinity,child:ElevatedButton.icon(onPressed:()=>Navigator.of(sheet).pop(true),icon:const Icon(Icons.check_rounded),label:const Text('Save Schedule')))])));}));if(ok==true){try{await updateFarmerPayoutSchedule(settlementId:row.id,date:selected,priority:priority,fundingStatus:funding,notes:note.text);await _refresh();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyAppError(e))));}}note.dispose();}
  Future<void> _clear(FarmerPayoutScheduleRow row)async{final c=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:Text('Clear ${row.number} schedule?'),content:TextField(controller:c,decoration:const InputDecoration(labelText:'Reason (optional)')),actions:[TextButton(onPressed:()=>Navigator.of(d).pop(false),child:const Text('Cancel')),ElevatedButton(onPressed:()=>Navigator.of(d).pop(true),child:const Text('Clear'))]));if(ok==true){try{await clearFarmerPayoutSchedule(row.id,c.text);await _refresh();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyAppError(e))));}}c.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:FarmColors.background,appBar:AppBar(title:const Text('Payout Schedule')),body:FutureBuilder<List<dynamic>>(future:_future,builder:(context,snapshot){if(snapshot.connectionState==ConnectionState.waiting&&snapshot.data==null)return const Center(child:CircularProgressIndicator());if(snapshot.hasError&&snapshot.data==null)return Center(child:Text(friendlyAppError(snapshot.error!)));final d=snapshot.data??const<dynamic>[];final s=d.isNotEmpty?d[0] as FarmerPayoutScheduleSummary:const FarmerPayoutScheduleSummary(openCount:0,unscheduledCount:0,overdueCount:0,due7:0,due30:0,funded:0,unfunded:0);final rows=d.length>1?d[1] as List<FarmerPayoutScheduleRow>:<FarmerPayoutScheduleRow>[];return RefreshIndicator(onRefresh:_refresh,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,16,16,110),children:[
    const FarmCard(padding:EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Farmer Payout Scheduling',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Schedule the existing settlement batches by priority and funding readiness. Payment is still completed through the Farmer Settlements screen.',style:TextStyle(color:FarmColors.mutedText,fontSize:10.5,height:1.35,fontWeight:FontWeight.w600))])),const SizedBox(height:12),FarmCard(padding:const EdgeInsets.all(14),child:Wrap(spacing:14,runSpacing:8,children:[Text('${s.openCount} open',style:const TextStyle(fontWeight:FontWeight.w900)),Text('${s.unscheduledCount} unscheduled',style:const TextStyle(fontWeight:FontWeight.w900)),Text('${s.overdueCount} overdue',style:const TextStyle(color:FarmColors.warning,fontWeight:FontWeight.w900)),Text('7-day ${formatJmd(s.due7)}',style:const TextStyle(fontWeight:FontWeight.w800)),Text('30-day ${formatJmd(s.due30)}',style:const TextStyle(fontWeight:FontWeight.w800)),Text('Funded ${formatJmd(s.funded)}',style:const TextStyle(color:FarmColors.success,fontWeight:FontWeight.w900)),Text('Unfunded ${formatJmd(s.unfunded)}',style:const TextStyle(fontWeight:FontWeight.w800))])),const SizedBox(height:12),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:{'open':'Open','overdue':'Overdue','unscheduled':'Unscheduled','funded':'Funded','all':'All'}.entries.map((e)=>Padding(padding:const EdgeInsets.only(right:7),child:ChoiceChip(label:Text(e.value),selected:_filter==e.key,onSelected:(_){setState((){_filter=e.key;_future=_load();});}))).toList())),const SizedBox(height:12),if(rows.isEmpty)const FarmEmptyState(icon:Icons.calendar_today_outlined,title:'No payout schedule rows',message:'Prepare farmer settlement batches first; open batches will appear here.')else ...rows.map((r){final color=_color(r);return Padding(padding:const EdgeInsets.only(bottom:9),child:FarmCard(padding:const EdgeInsets.all(13),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('${r.number} • ${r.displayName}',style:const TextStyle(fontWeight:FontWeight.w900))),Text(r.priority.toUpperCase(),style:TextStyle(color:color,fontSize:9,fontWeight:FontWeight.w900))]),const SizedBox(height:5),Text('${formatJmd(r.total)} • ${r.payoutCount} payout(s) • ${r.status.toUpperCase()}',style:const TextStyle(color:FarmColors.mutedText,fontSize:10,fontWeight:FontWeight.w700)),const SizedBox(height:3),Text('${_date(r.scheduledDate)} • ${r.fundingStatus.replaceAll('_',' ')}',style:TextStyle(color:color,fontSize:10,fontWeight:FontWeight.w800)),const SizedBox(height:8),Wrap(spacing:7,runSpacing:7,children:[ElevatedButton.icon(onPressed:()=>_schedule(r),icon:const Icon(Icons.calendar_today_outlined,size:16),label:Text(r.scheduledDate==null?'Schedule':'Update')),if(r.scheduledDate!=null)OutlinedButton(onPressed:()=>_clear(r),child:const Text('Clear'))])])));})]));}));
}
