part of harvest_place_app;

// ================================================================
// THE HARVEST PLACE JA
// PHASE 4J — PROFITABILITY INTELLIGENCE
// ================================================================

class WholesaleProfitabilityOverview {
  final int horizonDays; final int invoiceCount; final double netRevenue; final double procurementCost; final double packingCost; final double deliveryCost; final double otherCost; final double contributionMargin; final double contributionMarginPercent; final int lossInvoiceCount; final int lowMarginInvoiceCount; final double previousContribution; final double contributionChangePercent;
  const WholesaleProfitabilityOverview({required this.horizonDays,required this.invoiceCount,required this.netRevenue,required this.procurementCost,required this.packingCost,required this.deliveryCost,required this.otherCost,required this.contributionMargin,required this.contributionMarginPercent,required this.lossInvoiceCount,required this.lowMarginInvoiceCount,required this.previousContribution,required this.contributionChangePercent});
  factory WholesaleProfitabilityOverview.fromSupabase(Map<String,dynamic> d){ double n(dynamic v)=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??0; int i(dynamic v)=>v is num?v.toInt():int.tryParse(v?.toString()??'')??0; return WholesaleProfitabilityOverview(horizonDays:i(d['horizon_days']),invoiceCount:i(d['invoice_count']),netRevenue:n(d['net_revenue']),procurementCost:n(d['procurement_cost']),packingCost:n(d['packing_cost']),deliveryCost:n(d['delivery_cost']),otherCost:n(d['other_cost']),contributionMargin:n(d['contribution_margin']),contributionMarginPercent:n(d['contribution_margin_percent']),lossInvoiceCount:i(d['loss_invoice_count']),lowMarginInvoiceCount:i(d['low_margin_invoice_count']),previousContribution:n(d['previous_contribution']),contributionChangePercent:n(d['contribution_change_percent'])); }
}

class WholesaleProfitEntityRow {
  final String key; final String name; final int count; final double revenue; final double cost; final double overhead; final double contribution; final double marginPercent; final String status; final String detail;
  const WholesaleProfitEntityRow({required this.key,required this.name,required this.count,required this.revenue,required this.cost,required this.overhead,required this.contribution,required this.marginPercent,required this.status,required this.detail});
}

double _profitN(dynamic v)=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??0;
int _profitI(dynamic v)=>v is num?v.toInt():int.tryParse(v?.toString()??'')??0;

Future<WholesaleProfitabilityOverview> fetchWholesaleProfitabilityOverview(int days) async { await requireAdminAccess(); final r=await supabase.rpc('admin_wholesale_profitability_overview',params:{'p_days':days}); final list=r as List; return WholesaleProfitabilityOverview.fromSupabase(Map<String,dynamic>.from(list.first as Map)); }
Future<List<WholesaleProfitEntityRow>> fetchProfitCustomers(int days) async { await requireAdminAccess(); final r=await supabase.rpc('admin_wholesale_profitability_by_customer',params:{'p_days':days,'p_limit':100}); return (r as List).map((x){final d=Map<String,dynamic>.from(x as Map); return WholesaleProfitEntityRow(key:(d['business_account_id']??d['business_name']??'').toString(),name:(d['business_name']??'Wholesale business').toString(),count:_profitI(d['invoice_count']),revenue:_profitN(d['net_revenue']),cost:_profitN(d['procurement_cost']),overhead:_profitN(d['direct_overhead']),contribution:_profitN(d['contribution_margin']),marginPercent:_profitN(d['contribution_margin_percent']),status:(d['profitability_status']??'healthy').toString(),detail:'Avg invoice ${formatJmd(_profitN(d['average_invoice_value']))} • Delivery ${_profitN(d['delivery_cost_percent']).toStringAsFixed(1)}%');}).toList(); }
Future<List<WholesaleProfitEntityRow>> fetchProfitProducts(int days) async { await requireAdminAccess(); final r=await supabase.rpc('admin_wholesale_profitability_by_product',params:{'p_days':days,'p_limit':100}); return (r as List).map((x){final d=Map<String,dynamic>.from(x as Map); return WholesaleProfitEntityRow(key:'${d['product_name']}|${d['unit']}',name:(d['product_name']??'Produce').toString(),count:0,revenue:_profitN(d['net_revenue']),cost:_profitN(d['procurement_cost']),overhead:_profitN(d['allocated_overhead']),contribution:_profitN(d['contribution_margin']),marginPercent:_profitN(d['contribution_margin_percent']),status:(d['profitability_status']??'healthy').toString(),detail:'${_profitN(d['quantity_sold']).toStringAsFixed(1)} ${d['unit']??''} • Avg ${formatJmd(_profitN(d['average_selling_price']))}');}).toList(); }
Future<List<WholesaleProfitEntityRow>> fetchProfitSuppliers(int days) async { await requireAdminAccess(); final r=await supabase.rpc('admin_wholesale_profitability_by_supplier',params:{'p_days':days,'p_limit':100}); return (r as List).map((x){final d=Map<String,dynamic>.from(x as Map); final farm=(d['farm_name']??'').toString().trim(); return WholesaleProfitEntityRow(key:(d['farmer_id']??d['farmer_name']??'').toString(),name:'${d['farmer_name']??'Farmer'}${farm.isEmpty?'':' • $farm'}',count:_profitI(d['invoice_count']),revenue:_profitN(d['allocated_revenue']),cost:_profitN(d['procurement_cost']),overhead:_profitN(d['allocated_overhead']),contribution:_profitN(d['contribution_margin']),marginPercent:_profitN(d['contribution_margin_percent']),status:(d['profitability_status']??'healthy').toString(),detail:'${_profitN(d['quantity_supplied']).toStringAsFixed(1)} supplied • ${_profitI(d['invoice_count'])} invoice(s)');}).toList(); }
Future<List<WholesaleProfitEntityRow>> fetchProfitRoutes(int days) async { await requireAdminAccess(); final r=await supabase.rpc('admin_wholesale_profitability_by_route',params:{'p_days':days,'p_limit':100}); return (r as List).map((x){final d=Map<String,dynamic>.from(x as Map); return WholesaleProfitEntityRow(key:(d['route_key']??'').toString(),name:(d['route_label']??'Route').toString(),count:_profitI(d['invoice_count']),revenue:_profitN(d['net_revenue']),cost:0,overhead:_profitN(d['delivery_cost']),contribution:_profitN(d['contribution_margin']),marginPercent:_profitN(d['contribution_margin_percent']),status:(d['profitability_status']??'healthy').toString(),detail:'${_profitI(d['run_count'])} run(s) • Delivery ${_profitN(d['delivery_cost_percent']).toStringAsFixed(1)}% of revenue');}).toList(); }

class WholesaleProfitabilityIntelligenceScreen extends StatefulWidget { const WholesaleProfitabilityIntelligenceScreen({super.key}); @override State<WholesaleProfitabilityIntelligenceScreen> createState()=>_WholesaleProfitabilityIntelligenceScreenState(); }
class _WholesaleProfitabilityIntelligenceScreenState extends State<WholesaleProfitabilityIntelligenceScreen>{
  int _days=30; late Future<List<dynamic>> _future; String _view='customers';
  @override void initState(){super.initState();_future=_load();}
  Future<List<dynamic>> _load()=>Future.wait<dynamic>([fetchWholesaleProfitabilityOverview(_days),fetchProfitCustomers(_days),fetchProfitProducts(_days),fetchProfitSuppliers(_days),fetchProfitRoutes(_days)]);
  Future<void> _refresh() async {final n=_load();setState(()=>_future=n);await n;}
  Color _c(String s)=>s=='loss'?FarmColors.danger:s=='low'?FarmColors.warning:FarmColors.success;
  @override Widget build(BuildContext context){return Scaffold(backgroundColor:FarmColors.background,appBar:AppBar(title:const Text('Profitability Intelligence')),body:FutureBuilder<List<dynamic>>(future:_future,builder:(context,s){if(s.connectionState==ConnectionState.waiting&&s.data==null)return const Center(child:CircularProgressIndicator());if(s.hasError&&s.data==null)return Center(child:Text(friendlyAppError(s.error!)));final d=s.data??const<dynamic>[];if(d.length<5)return const SizedBox.shrink();final o=d[0] as WholesaleProfitabilityOverview;final groups=<String,List<WholesaleProfitEntityRow>>{'customers':d[1] as List<WholesaleProfitEntityRow>,'products':d[2] as List<WholesaleProfitEntityRow>,'suppliers':d[3] as List<WholesaleProfitEntityRow>,'routes':d[4] as List<WholesaleProfitEntityRow>};final rows=groups[_view]??const<WholesaleProfitEntityRow>[];return RefreshIndicator(onRefresh:_refresh,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,16,16,110),children:[
    FarmCard(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Commercial Profitability',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('Contribution after customer credits, supplier recoveries and recorded direct invoice costs. Supplier/product views allocate overhead for decision support.',style:TextStyle(color:FarmColors.mutedText,fontSize:10.5,height:1.35,fontWeight:FontWeight.w600)),const SizedBox(height:10),Text('${formatJmd(o.contributionMargin)} • ${o.contributionMarginPercent.toStringAsFixed(1)}% margin',style:TextStyle(color:o.contributionMargin<0?FarmColors.danger:FarmColors.primary,fontWeight:FontWeight.w900)),Text('Previous-period change ${o.contributionChangePercent>=0?'+':''}${o.contributionChangePercent.toStringAsFixed(1)}%',style:TextStyle(color:o.contributionChangePercent<0?FarmColors.warning:FarmColors.success,fontSize:10.5,fontWeight:FontWeight.w800))])),
    const SizedBox(height:10),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[7,30,90].map((x)=>Padding(padding:const EdgeInsets.only(right:7),child:ChoiceChip(label:Text('$x days'),selected:_days==x,onSelected:(_){setState((){_days=x;_future=_load();});}))).toList())),
    const SizedBox(height:10),FarmCard(padding:const EdgeInsets.all(12),child:Wrap(spacing:14,runSpacing:8,children:[Text('Revenue ${formatJmd(o.netRevenue)}',style:const TextStyle(fontWeight:FontWeight.w800)),Text('Produce ${formatJmd(o.procurementCost)}',style:const TextStyle(fontWeight:FontWeight.w800)),Text('Delivery ${formatJmd(o.deliveryCost)}',style:const TextStyle(fontWeight:FontWeight.w800)),Text('${o.lossInvoiceCount} loss',style:const TextStyle(color:FarmColors.danger,fontWeight:FontWeight.w900)),Text('${o.lowMarginInvoiceCount} low',style:const TextStyle(color:FarmColors.warning,fontWeight:FontWeight.w900))])),
    const SizedBox(height:12),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:['customers','products','suppliers','routes'].map((x)=>Padding(padding:const EdgeInsets.only(right:7),child:ChoiceChip(label:Text(x[0].toUpperCase()+x.substring(1)),selected:_view==x,onSelected:(_)=>setState(()=>_view=x)))).toList())),const SizedBox(height:12),
    if(rows.isEmpty) const FarmEmptyState(icon:Icons.analytics_outlined,title:'No profitability history yet',message:'Issued wholesale invoices with cost data will appear here.') else ...rows.map((r)=>Padding(padding:const EdgeInsets.only(bottom:9),child:FarmCard(padding:const EdgeInsets.all(13),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(r.name,style:const TextStyle(fontWeight:FontWeight.w900))),Text('${r.marginPercent.toStringAsFixed(1)}%',style:TextStyle(color:_c(r.status),fontWeight:FontWeight.w900))]),const SizedBox(height:4),Text(r.detail,style:const TextStyle(color:FarmColors.mutedText,fontSize:10,fontWeight:FontWeight.w700)),const SizedBox(height:6),Wrap(spacing:10,runSpacing:5,children:[Text('Revenue ${formatJmd(r.revenue)}',style:const TextStyle(fontSize:10.5,fontWeight:FontWeight.w800)),if(r.cost>0)Text('Produce ${formatJmd(r.cost)}',style:const TextStyle(fontSize:10.5,fontWeight:FontWeight.w800)),if(r.overhead>0)Text('Overhead ${formatJmd(r.overhead)}',style:const TextStyle(fontSize:10.5,fontWeight:FontWeight.w800)),Text('Contribution ${formatJmd(r.contribution)}',style:TextStyle(color:_c(r.status),fontSize:10.5,fontWeight:FontWeight.w900))])]))))
  ]));}));}
}
