part of harvest_place_app;

// ================================================================
// THE HARVEST PLACE JA
// PHASE 4E — REFUNDS + RETURN FINANCE
// ================================================================

class WholesaleReturnFinanceRow {
  final String returnId,businessName,invoiceId,invoiceNumber,returnStatus,returnReason,creditNoteId,creditNumber,financeStatus;
  final double physicalReturnValue,creditAmount,invoicePaidAmount,invoiceNetTotal,customerCreditBalance,refundsPaid,refundDue;
  const WholesaleReturnFinanceRow({required this.returnId,required this.businessName,required this.invoiceId,required this.invoiceNumber,required this.returnStatus,required this.returnReason,required this.physicalReturnValue,required this.creditNoteId,required this.creditNumber,required this.creditAmount,required this.invoicePaidAmount,required this.invoiceNetTotal,required this.customerCreditBalance,required this.refundsPaid,required this.refundDue,required this.financeStatus});
  factory WholesaleReturnFinanceRow.fromSupabase(Map<String,dynamic>d){double n(dynamic v)=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??0;return WholesaleReturnFinanceRow(returnId:(d['return_id']??'').toString(),businessName:(d['business_name']??'Wholesale business').toString(),invoiceId:(d['invoice_id']??'').toString(),invoiceNumber:(d['invoice_number']??'').toString(),returnStatus:(d['return_status']??'').toString(),returnReason:(d['return_reason']??'').toString(),physicalReturnValue:n(d['physical_return_value']),creditNoteId:(d['credit_note_id']??'').toString(),creditNumber:(d['credit_number']??'').toString(),creditAmount:n(d['credit_amount']),invoicePaidAmount:n(d['invoice_paid_amount']),invoiceNetTotal:n(d['invoice_net_total']),customerCreditBalance:n(d['customer_credit_balance']),refundsPaid:n(d['refunds_paid']),refundDue:n(d['refund_due']),financeStatus:(d['finance_status']??'needs_credit').toString());}
}
class WholesaleRefundRow {
  final String id,refundNumber,creditNoteId,creditNumber,invoiceId,invoiceNumber,businessName,paymentMethod,paymentReference,status,notes; final double amount; final DateTime? paidAt;
  const WholesaleRefundRow({required this.id,required this.refundNumber,required this.creditNoteId,required this.creditNumber,required this.invoiceId,required this.invoiceNumber,required this.businessName,required this.amount,required this.paymentMethod,required this.paymentReference,required this.status,required this.paidAt,required this.notes});
  factory WholesaleRefundRow.fromSupabase(Map<String,dynamic>d){double n(dynamic v)=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??0;return WholesaleRefundRow(id:(d['refund_id']??'').toString(),refundNumber:(d['refund_number']??'').toString(),creditNoteId:(d['credit_note_id']??'').toString(),creditNumber:(d['credit_number']??'').toString(),invoiceId:(d['invoice_id']??'').toString(),invoiceNumber:(d['invoice_number']??'').toString(),businessName:(d['business_name']??'Wholesale business').toString(),amount:n(d['amount']),paymentMethod:(d['payment_method']??'').toString(),paymentReference:(d['payment_reference']??'').toString(),status:(d['status']??'paid').toString(),paidAt:DateTime.tryParse((d['paid_at']??'').toString()),notes:(d['notes']??'').toString());}
}
Future<List<WholesaleReturnFinanceRow>> fetchWholesaleReturnFinance({String status='all'}) async {await requireAdminAccess();final r=await supabase.rpc('admin_list_return_finance',params:{'p_status':status,'p_limit':200});return (r as List).map((x)=>WholesaleReturnFinanceRow.fromSupabase(Map<String,dynamic>.from(x as Map))).toList();}
Future<List<WholesaleRefundRow>> fetchWholesaleRefunds() async {await requireAdminAccess();final r=await supabase.rpc('admin_list_wholesale_refunds',params:{'p_limit':200});return (r as List).map((x)=>WholesaleRefundRow.fromSupabase(Map<String,dynamic>.from(x as Map))).toList();}
Future<void> recordWholesaleRefund({required String creditNoteId,required double amount,required String method,required String reference,String notes=''}) async {await requireAdminAccess();await supabase.rpc('admin_record_wholesale_refund',params:{'p_credit_note_id':creditNoteId,'p_amount':amount,'p_payment_method':method.trim(),'p_payment_reference':reference.trim(),'p_notes':notes.trim()});}

class WholesaleReturnFinanceScreen extends StatefulWidget{const WholesaleReturnFinanceScreen({super.key});@override State<WholesaleReturnFinanceScreen> createState()=>_WholesaleReturnFinanceScreenState();}
class _WholesaleReturnFinanceScreenState extends State<WholesaleReturnFinanceScreen>{
  late Future<List<dynamic>> _future;String _status='all';@override void initState(){super.initState();_future=_load();}Future<List<dynamic>> _load()=>Future.wait<dynamic>([fetchWholesaleReturnFinance(status:_status),fetchWholesaleRefunds()]);Future<void> _refresh()async{final n=_load();setState(()=>_future=n);await n;}
  Color _color(String s){if(s=='refund_due')return FarmColors.warning;if(s=='needs_credit')return FarmColors.danger;return FarmColors.success;}
  Future<void> _refund(WholesaleReturnFinanceRow row) async {final amount=TextEditingController(text:row.refundDue.toStringAsFixed(2));final reference=TextEditingController();final notes=TextEditingController();String method='bank_transfer';final ok=await showDialog<bool>(context:context,builder:(dc)=>StatefulBuilder(builder:(context,setLocal)=>AlertDialog(title:Text('Refund ${row.creditNumber}'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Available customer credit: ${formatJmd(row.refundDue)}',style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:10),TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Refund amount')),const SizedBox(height:8),DropdownButtonFormField<String>(value:method,decoration:const InputDecoration(labelText:'Method'),items:const [DropdownMenuItem(value:'bank_transfer',child:Text('Bank transfer')),DropdownMenuItem(value:'cash',child:Text('Cash')),DropdownMenuItem(value:'cheque',child:Text('Cheque')),DropdownMenuItem(value:'other',child:Text('Other'))],onChanged:(v)=>setLocal(()=>method=v??method)),const SizedBox(height:8),TextField(controller:reference,decoration:const InputDecoration(labelText:'Transaction / reference')),const SizedBox(height:8),TextField(controller:notes,maxLines:2,decoration:const InputDecoration(labelText:'Refund note'))])),actions:[TextButton(onPressed:()=>Navigator.of(dc).pop(false),child:const Text('Cancel')),ElevatedButton(onPressed:()=>Navigator.of(dc).pop(true),child:const Text('Record Refund'))])));if(ok==true){final v=double.tryParse(amount.text.trim().replaceAll(',',''))??0;if(v>0&&reference.text.trim().isNotEmpty){try{await recordWholesaleRefund(creditNoteId:row.creditNoteId,amount:v,method:method,reference:reference.text,notes:notes.text);await _refresh();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyAppError(e))));}}}amount.dispose();reference.dispose();notes.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:FarmColors.background,appBar:AppBar(title:const Text('Return Finance & Refunds')),body:FutureBuilder<List<dynamic>>(future:_future,builder:(context,s){if(s.connectionState==ConnectionState.waiting&&s.data==null)return const Center(child:CircularProgressIndicator());if(s.hasError&&s.data==null)return Center(child:Text(friendlyAppError(s.error!)));final d=s.data??const<dynamic>[];final rows=d.isNotEmpty?d[0] as List<WholesaleReturnFinanceRow>:<WholesaleReturnFinanceRow>[];final refunds=d.length>1?d[1] as List<WholesaleRefundRow>:<WholesaleRefundRow>[];return RefreshIndicator(onRefresh:_refresh,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,16,16,110),children:[
    const FarmCard(padding:EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Return-to-cash reconciliation',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('A credit note reduces the sale. A refund is recorded only when confirmed payments create a customer credit balance.',style:TextStyle(color:FarmColors.mutedText,fontSize:10.5,height:1.35,fontWeight:FontWeight.w600))])),const SizedBox(height:12),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:{'all':'All','needs_credit':'Needs Credit','refund_due':'Refund Due','settled':'Settled'}.entries.map((e)=>Padding(padding:const EdgeInsets.only(right:7),child:ChoiceChip(label:Text(e.value),selected:_status==e.key,onSelected:(_){setState((){_status=e.key;_future=_load();});}))).toList())),const SizedBox(height:12),
    if(rows.isEmpty)const FarmEmptyState(icon:Icons.assignment_return_outlined,title:'No return finance rows',message:'Delivered returns will appear here when finance review is required.')else ...rows.map((r)=>Padding(padding:const EdgeInsets.only(bottom:9),child:FarmCard(padding:const EdgeInsets.all(13),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('${r.invoiceNumber} • ${r.businessName}',style:const TextStyle(fontWeight:FontWeight.w900))),Text(r.financeStatus.replaceAll('_',' ').toUpperCase(),style:TextStyle(color:_color(r.financeStatus),fontSize:9,fontWeight:FontWeight.w900))]),const SizedBox(height:6),Text('Return ${formatJmd(r.physicalReturnValue)} • Credit ${formatJmd(r.creditAmount)} • Paid ${formatJmd(r.invoicePaidAmount)}',style:const TextStyle(color:FarmColors.mutedText,fontSize:10,fontWeight:FontWeight.w700)),if(r.refundDue>0.005)...[const SizedBox(height:8),OutlinedButton.icon(onPressed:r.creditNoteId.isEmpty?null:()=>_refund(r),icon:const Icon(Icons.payments_outlined,size:16),label:Text('Refund ${formatJmd(r.refundDue)}'))]])))),const SizedBox(height:18),const Text('Refund History',style:TextStyle(fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:8),if(refunds.isEmpty)const FarmCard(child:Text('No customer refunds recorded.'))else ...refunds.take(40).map((r)=>Padding(padding:const EdgeInsets.only(bottom:8),child:FarmCard(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${r.refundNumber} • ${r.businessName}',style:const TextStyle(fontWeight:FontWeight.w900)),Text('${r.creditNumber} • ${r.paymentMethod} • ${r.paymentReference}',style:const TextStyle(color:FarmColors.mutedText,fontSize:9.8,fontWeight:FontWeight.w700))])),Text(formatJmd(r.amount),style:const TextStyle(fontWeight:FontWeight.w900))]))))
  ]));}));
}
