part of harvest_place_app;

// ================================================================
// THE HARVEST PLACE JA
// PHASE 5H — FORECAST CALIBRATION + DATA QUALITY
// ================================================================

class ForecastCalibrationRow{
  final int horizonDays,maturedCount,underCount,overCount; final double accuracy,bias,bandCoverage,confidence,confidenceGap; final String status,guidance;
  const ForecastCalibrationRow({required this.horizonDays,required this.maturedCount,required this.underCount,required this.overCount,required this.accuracy,required this.bias,required this.bandCoverage,required this.confidence,required this.confidenceGap,required this.status,required this.guidance});
  factory ForecastCalibrationRow.fromSupabase(Map<String,dynamic>d){int i(dynamic v)=>v is num?v.toInt():int.tryParse('${v??''}')??0;double n(dynamic v)=>v is num?v.toDouble():double.tryParse('${v??''}')??0;return ForecastCalibrationRow(horizonDays:i(d['horizon_days']),maturedCount:i(d['matured_snapshot_count']),underCount:i(d['underforecast_count']),overCount:i(d['overforecast_count']),accuracy:n(d['average_accuracy_percent']),bias:n(d['average_bias_percent']),bandCoverage:n(d['within_band_percent']),confidence:n(d['average_calibrated_confidence']),confidenceGap:n(d['confidence_gap']),status:(d['calibration_status']??'insufficient_data').toString(),guidance:(d['guidance']??'').toString());}
}
class ForecastDataQualitySummary{
  final int horizonDays,historyDays,productCount,lowConfidenceCount,noHistoryCount,missingUnitCount,maturedCount;final double accuracy,bandCoverage,score;final String status,guidance;
  const ForecastDataQualitySummary({required this.horizonDays,required this.historyDays,required this.productCount,required this.lowConfidenceCount,required this.noHistoryCount,required this.missingUnitCount,required this.maturedCount,required this.accuracy,required this.bandCoverage,required this.score,required this.status,required this.guidance});
  factory ForecastDataQualitySummary.fromSupabase(Map<String,dynamic>d){int i(dynamic v)=>v is num?v.toInt():int.tryParse('${v??''}')??0;double n(dynamic v)=>v is num?v.toDouble():double.tryParse('${v??''}')??0;return ForecastDataQualitySummary(horizonDays:i(d['horizon_days']),historyDays:i(d['history_days']),productCount:i(d['demand_product_count']),lowConfidenceCount:i(d['low_confidence_product_count']),noHistoryCount:i(d['no_fulfilled_history_product_count']),missingUnitCount:i(d['missing_unit_product_count']),maturedCount:i(d['matured_snapshot_count']),accuracy:n(d['average_accuracy_percent']),bandCoverage:n(d['within_band_percent']),score:n(d['data_quality_score']),status:(d['data_quality_status']??'building_history').toString(),guidance:(d['guidance']??'').toString());}
}
Future<List<ForecastCalibrationRow>> fetchForecastCalibrationRows()async{await requireAdminAccess();final r=await supabase.rpc('admin_forecast_calibration_by_horizon');return(r as List? ?? const[]).map((e)=>ForecastCalibrationRow.fromSupabase(Map<String,dynamic>.from(e as Map))).toList();}
Future<ForecastDataQualitySummary> fetchForecastDataQuality(int days)async{await requireAdminAccess();final r=await supabase.rpc('admin_forecast_data_quality_summary',params:{'p_horizon_days':days,'p_history_days':90});if(r is List&&r.isNotEmpty)return ForecastDataQualitySummary.fromSupabase(Map<String,dynamic>.from(r.first as Map));if(r is Map)return ForecastDataQualitySummary.fromSupabase(Map<String,dynamic>.from(r));throw Exception('Forecast data quality could not be loaded.');}

class ForecastCalibrationScreen extends StatefulWidget{final int initialHorizonDays;const ForecastCalibrationScreen({super.key,this.initialHorizonDays=30});@override State<ForecastCalibrationScreen> createState()=>_ForecastCalibrationScreenState();}
class _ForecastCalibrationScreenState extends State<ForecastCalibrationScreen>{late int _days;late Future<(ForecastDataQualitySummary,List<ForecastCalibrationRow>)> _future;@override void initState(){super.initState();_days=widget.initialHorizonDays;_load();}void _load(){_future=Future.wait([fetchForecastDataQuality(_days),fetchForecastCalibrationRows()]).then((v)=>(v[0] as ForecastDataQualitySummary,v[1] as List<ForecastCalibrationRow>));}Future<void>_refresh()async{setState(_load);await _future;}Color _c(String s)=>s=='needs_calibration'||s=='attention'?FarmColors.danger:s=='watch'||s=='building_history'||s=='insufficient_data'?FarmColors.warning:FarmColors.success;
  Widget _metric(String label,String value)=>Container(width:145,padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:FarmColors.cardSoft,borderRadius:BorderRadius.circular(13),border:Border.all(color:FarmColors.line)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:const TextStyle(fontWeight:FontWeight.w900,color:FarmColors.ink)),Text(label,style:const TextStyle(fontSize:9.5,color:FarmColors.mutedText))]));
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Forecast Calibration')),body:FutureBuilder<(ForecastDataQualitySummary,List<ForecastCalibrationRow>)>(future:_future,builder:(context,s){if(s.connectionState==ConnectionState.waiting&&s.data==null)return const Center(child:CircularProgressIndicator());if(s.hasError&&s.data==null)return Center(child:Text(friendlyAppError(s.error!)));final data=s.data;if(data==null)return const SizedBox.shrink();final q=data.$1;final rows=data.$2;return RefreshIndicator(onRefresh:_refresh,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,16,16,100),children:[
    FarmCard(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.tune_rounded,color:FarmColors.primary),SizedBox(width:10),Expanded(child:Text('Forecast calibration',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900,color:FarmColors.ink)))]),const SizedBox(height:6),const Text('Measures forecast accuracy, bias and confidence-band coverage. Calibration becomes meaningful only after captured forecasts mature.',style:TextStyle(color:FarmColors.mutedText,fontSize:10.5,height:1.35)),const SizedBox(height:12),Wrap(spacing:8,children:[7,30,60,90].map((d)=>ChoiceChip(label:Text('$d days'),selected:_days==d,onSelected:(_){setState((){_days=d;_load();});})).toList()),const SizedBox(height:12),Wrap(spacing:8,runSpacing:8,children:[_metric('Data quality','${q.score.toStringAsFixed(0)}%'),_metric('Products','${q.productCount}'),_metric('Low confidence','${q.lowConfidenceCount}'),_metric('No history','${q.noHistoryCount}'),_metric('Matured snapshots','${q.maturedCount}'),_metric('Avg accuracy','${q.accuracy.toStringAsFixed(1)}%')]),const SizedBox(height:10),Text(q.guidance,style:TextStyle(color:_c(q.status),fontWeight:FontWeight.w800,fontSize:10.5,height:1.35))])),
    const SizedBox(height:12),...rows.map((r)=>Padding(padding:const EdgeInsets.only(bottom:8),child:FarmCard(padding:const EdgeInsets.all(13),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('${r.horizonDays}-day horizon',style:const TextStyle(fontWeight:FontWeight.w900,color:FarmColors.ink))),Text(r.status.replaceAll('_',' ').toUpperCase(),style:TextStyle(color:_c(r.status),fontWeight:FontWeight.w900,fontSize:9))]),const SizedBox(height:7),Wrap(spacing:14,runSpacing:6,children:[Text('${r.maturedCount} matured',style:const TextStyle(fontSize:10)),Text('${r.accuracy.toStringAsFixed(1)}% accuracy',style:const TextStyle(fontSize:10)),Text('${r.bandCoverage.toStringAsFixed(1)}% in band',style:const TextStyle(fontSize:10)),Text('${r.bias.toStringAsFixed(1)}% bias',style:const TextStyle(fontSize:10))]),const SizedBox(height:7),Text(r.guidance,style:const TextStyle(color:FarmColors.mutedText,fontSize:10,height:1.35))])))).toList()
  ]));}));
}
