part of harvest_place_app;

// ================================================================
// THE HARVEST PLACE JA
// PHASE 5I — RELEASE READINESS + RC SNAPSHOTS
// ================================================================

class ReleaseReadinessSummary{
  final int horizonDays,blockerCount,warningCount,passCount,totalChecks,maturedCount,criticalAlerts,highAlerts;final double score,financeHealth,reconciliation,dataQuality,forecastAccuracy;final String status,dataQualityStatus,recommendation;
  const ReleaseReadinessSummary({required this.horizonDays,required this.blockerCount,required this.warningCount,required this.passCount,required this.totalChecks,required this.maturedCount,required this.criticalAlerts,required this.highAlerts,required this.score,required this.financeHealth,required this.reconciliation,required this.dataQuality,required this.forecastAccuracy,required this.status,required this.dataQualityStatus,required this.recommendation});
  factory ReleaseReadinessSummary.fromSupabase(Map<String,dynamic>d){int i(dynamic v)=>v is num?v.toInt():int.tryParse('${v??''}')??0;double n(dynamic v)=>v is num?v.toDouble():double.tryParse('${v??''}')??0;return ReleaseReadinessSummary(horizonDays:i(d['horizon_days']),blockerCount:i(d['blocker_count']),warningCount:i(d['warning_count']),passCount:i(d['validation_pass_count']),totalChecks:i(d['validation_total_checks']),maturedCount:i(d['forecast_matured_snapshot_count']),criticalAlerts:i(d['critical_business_alert_count']),highAlerts:i(d['high_business_alert_count']),score:n(d['release_score']),financeHealth:n(d['finance_health_score']),reconciliation:n(d['finance_reconciliation_percent']),dataQuality:n(d['forecast_data_quality_score']),forecastAccuracy:n(d['forecast_accuracy_percent']),status:(d['release_status']??'conditional').toString(),dataQualityStatus:(d['forecast_data_quality_status']??'building_history').toString(),recommendation:(d['recommendation']??'').toString());}
}
class ReleaseReadinessSnapshot{final String number,status,note;final double score;final int blockers,warnings;final DateTime? capturedAt;const ReleaseReadinessSnapshot({required this.number,required this.status,required this.note,required this.score,required this.blockers,required this.warnings,required this.capturedAt});factory ReleaseReadinessSnapshot.fromSupabase(Map<String,dynamic>d){double n(dynamic v)=>v is num?v.toDouble():double.tryParse('${v??''}')??0;int i(dynamic v)=>v is num?v.toInt():int.tryParse('${v??''}')??0;return ReleaseReadinessSnapshot(number:(d['snapshot_number']??'').toString(),status:(d['release_status']??'conditional').toString(),note:(d['note']??'').toString(),score:n(d['release_score']),blockers:i(d['blocker_count']),warnings:i(d['warning_count']),capturedAt:DateTime.tryParse('${d['captured_at']??''}'));}}
Future<ReleaseReadinessSummary> fetchReleaseReadiness(int days)async{await requireAdminAccess();final r=await supabase.rpc('admin_release_readiness_summary',params:{'p_horizon_days':days});if(r is List&&r.isNotEmpty)return ReleaseReadinessSummary.fromSupabase(Map<String,dynamic>.from(r.first as Map));if(r is Map)return ReleaseReadinessSummary.fromSupabase(Map<String,dynamic>.from(r));throw Exception('Release readiness could not be loaded.');}
Future<List<ReleaseReadinessSnapshot>> fetchReleaseReadinessSnapshots()async{await requireAdminAccess();final r=await supabase.rpc('admin_list_release_readiness_snapshots',params:{'p_limit':20});return(r as List? ?? const[]).map((e)=>ReleaseReadinessSnapshot.fromSupabase(Map<String,dynamic>.from(e as Map))).toList();}
Future<void>captureReleaseReadiness(int days,{String note=''})async{await requireAdminAccess();await supabase.rpc('admin_capture_release_readiness_snapshot',params:{'p_horizon_days':days,'p_note':note});}

class ReleaseReadinessScreen extends StatefulWidget{final int initialHorizonDays;const ReleaseReadinessScreen({super.key,this.initialHorizonDays=30});@override State<ReleaseReadinessScreen> createState()=>_ReleaseReadinessScreenState();}
class _ReleaseReadinessScreenState extends State<ReleaseReadinessScreen>{late int _days;late Future<(ReleaseReadinessSummary,List<ReleaseReadinessSnapshot>)> _future;bool _saving=false;@override void initState(){super.initState();_days=widget.initialHorizonDays;_load();}void _load(){_future=Future.wait([fetchReleaseReadiness(_days),fetchReleaseReadinessSnapshots()]).then((v)=>(v[0] as ReleaseReadinessSummary,v[1] as List<ReleaseReadinessSnapshot>));}Future<void>_refresh()async{setState(_load);await _future;}Color _c(String s)=>s=='blocked'?FarmColors.danger:s=='conditional'?FarmColors.warning:FarmColors.success;Future<void>_capture()async{if(_saving)return;setState(()=>_saving=true);try{await captureReleaseReadiness(_days,note:'Release candidate checkpoint');if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Release candidate snapshot captured.')));await _refresh();}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(friendlyAppError(e))));}finally{if(mounted)setState(()=>_saving=false);}}
Widget _m(String l,String v)=>Container(width:145,padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:FarmColors.cardSoft,borderRadius:BorderRadius.circular(13),border:Border.all(color:FarmColors.line)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(v,style:const TextStyle(fontWeight:FontWeight.w900,color:FarmColors.ink)),Text(l,style:const TextStyle(fontSize:9.5,color:FarmColors.mutedText))]));
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Release Readiness')),body:FutureBuilder<(ReleaseReadinessSummary,List<ReleaseReadinessSnapshot>)>(future:_future,builder:(context,s){if(s.connectionState==ConnectionState.waiting&&s.data==null)return const Center(child:CircularProgressIndicator());if(s.hasError&&s.data==null)return Center(child:Text(friendlyAppError(s.error!)));final data=s.data;if(data==null)return const SizedBox.shrink();final r=data.$1;final history=data.$2;return RefreshIndicator(onRefresh:_refresh,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,16,16,100),children:[
 FarmCard(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.verified_outlined,color:FarmColors.primary,size:28),SizedBox(width:10),Expanded(child:Text('HPJ Release Candidate',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900,color:FarmColors.ink)))]),const SizedBox(height:8),Text(r.status.replaceAll('_',' ').toUpperCase(),style:TextStyle(color:_c(r.status),fontWeight:FontWeight.w900,fontSize:12)),const SizedBox(height:5),Text(r.recommendation,style:const TextStyle(color:FarmColors.mutedText,fontSize:10.5,height:1.35)),const SizedBox(height:12),Wrap(spacing:8,children:[7,30,60,90].map((d)=>ChoiceChip(label:Text('$d days'),selected:_days==d,onSelected:(_){setState((){_days=d;_load();});})).toList()),const SizedBox(height:12),Wrap(spacing:8,runSpacing:8,children:[_m('Release score','${r.score.toStringAsFixed(0)}%'),_m('Blockers','${r.blockerCount}'),_m('Warnings','${r.warningCount}'),_m('Finance health','${r.financeHealth.toStringAsFixed(0)}%'),_m('Reconciled','${r.reconciliation.toStringAsFixed(0)}%'),_m('Forecast data','${r.dataQuality.toStringAsFixed(0)}%')]),const SizedBox(height:12),SizedBox(width:double.infinity,child:ElevatedButton.icon(onPressed:_saving?null:_capture,icon:const Icon(Icons.save_outlined),label:Text(_saving?'Saving…':'Capture RC Snapshot')))])),
 const SizedBox(height:12),FarmCard(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Testing gate',style:TextStyle(fontWeight:FontWeight.w900,color:FarmColors.ink)),const SizedBox(height:7),Text('${r.passCount}/${r.totalChecks} validation checks pass • ${r.maturedCount} matured forecast snapshot(s) • ${r.criticalAlerts} critical business alert(s) • ${r.highAlerts} high alert(s)',style:const TextStyle(color:FarmColors.mutedText,fontSize:10.5,height:1.35)),const SizedBox(height:6),const Text('Business alerts and limited forecast history are test observations. Only release-validation failures are automatic blockers.',style:TextStyle(color:FarmColors.mutedText,fontSize:9.5,height:1.35))])),
 if(history.isNotEmpty)...[const SizedBox(height:12),const Text('Recent RC snapshots',style:TextStyle(fontWeight:FontWeight.w900,color:FarmColors.ink)),const SizedBox(height:8),...history.take(10).map((h)=>Padding(padding:const EdgeInsets.only(bottom:7),child:FarmCard(padding:const EdgeInsets.all(12),child:Row(children:[Icon(h.status=='blocked'?Icons.error_outline:Icons.check_circle_outline,color:_c(h.status)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(h.number,style:const TextStyle(fontWeight:FontWeight.w900,color:FarmColors.ink)),Text('${h.score.toStringAsFixed(0)}% • ${h.blockers} blocker(s) • ${h.warnings} warning(s)',style:const TextStyle(fontSize:9.5,color:FarmColors.mutedText))]))])))).toList()]
]));}));}
